import mongoose, { Document, Schema } from 'mongoose';

export interface IPoll extends Document {
  meetingId: string;
  question: string;
  options: string[];
  correctOption?: number;
  createdAt: Date;
  endedAt?: Date;
  isAutoGenerated: boolean;
}

const PollSchema: Schema = new Schema({
  meetingId: { type: String, required: true },
  question: { type: String, required: true },
  options: { type: [String], required: true },
  correctOption: { type: Number },
  createdAt: { type: Date, default: Date.now },
  endedAt: { type: Date },
  isAutoGenerated: { type: Boolean, default: false }
});

export default mongoose.model<IPoll>('Poll', PollSchema);