import axios from 'axios';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000';

const api = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json'
  }
});

// Meetings
export const createMeeting = (meetingId: string, hostId: string) => {
  return api.post('/meetings', { meetingId, hostId });
};

export const endMeeting = (meetingId: string) => {
  return api.patch(`/meetings/${meetingId}/end`);
};

export const addParticipant = (meetingId: string, userId: string) => {
  return api.patch(`/meetings/${meetingId}/participants`, { userId });
};

export const getMeeting = (meetingId: string) => {
  return api.get(`/meetings/${meetingId}`);
};

// Polls
export const getMeetingPolls = (meetingId: string) => {
  return api.get(`/polls/meeting/${meetingId}`);
};

export const createPoll = (pollData: {
  meetingId: string;
  question: string;
  options: string[];
  correctOption?: number;
  isAutoGenerated: boolean;
}) => {
  return api.post('/polls', pollData);
};

export const endPoll = (pollId: string) => {
  return api.patch(`/polls/${pollId}/end`);
};

export const getPollResults = (pollId: string) => {
  return api.get(`/polls/${pollId}/results`);
};

export default api;